config/routes.rb
Rails.application.routes.draw do
  root 'topics#index'
  resources :topics do
    collection do
       post :sort
    end
  end
  resources :evokes
  resources :categories do
    collection do
      get :manage
      post :sort
    end

  end

end

app/models/choice.rb
# == Schema Information
#
# Table name: choices
#
#  id            :integer          not null
#  body          :text
#  correct       :boolean          default(FALSE), not null
#  evoke_id      :integer
#  explanation   :text
#  sort_order    :string
#  bodyx         :string
#  explanationx  :string
#  body_y        :string
#  explanation_y :string
#

class Choice < ActiveRecord::Base
  scope :right, -> { where(correct: true) }
  scope :wrong, -> { where('correct = false or correct is null') }

  belongs_to :evoke

  validates :body, presence: true

  def overlaid_body
    if evoke.overlay.nil?
      (evoke.vignette.present? && !evoke.vignette.overlay.nil? ? body_y % eval(evoke.vignette.overlay.to_json) : body).html_safe
    else
      (body_y % eval(evoke.overlay.to_json)).html_safe
    end
  end

  def overlaid_explanation
    if evoke.overlay.nil?
      (evoke.vignette.present? && !evoke.vignette.overlay.nil? ? explanation_y % eval(evoke.vignette.overlay.to_json) : explanation).html_safe
    else
      (explanation_y % eval(evoke.overlay.to_json)).html_safe
    end
  end
end

app/models/evoke.rb
# == Schema Information
#
# Table name: evokes
#
#  evoke_id    :integer          not null, primary key
#  topic_id    :integer
#  stem        :text             not null
#  tute        :text
#  sort_order  :integer          default(0), not null
#  difficulty  :integer          default(40), not null
#  active      :boolean          default(TRUE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  hint        :text
#  vignette_id :integer
#  custom      :boolean          default(FALSE)
#  source      :string           default("SG")
#  hintx       :string
#  tutex       :string
#  stemx       :string
#  stem_y      :string
#  tute_y      :string
#  hint_y      :string
#  overlay     :jsonb
#  mobile      :boolean          default(TRUE)
#  original_id :integer
#

class Evoke < ActiveRecord::Base
  self.primary_key = 'evoke_id'

  default_scope { where(active: true) }
  # default_scope { order(evoke_id: :asc) }
  scope :random, -> { order('random()') }
  scope :active, -> { where(active: true) }

  # Answer choices for this evoke
  has_many :choices, dependent: :destroy
  has_many :learnings, dependent: :destroy

  belongs_to :topic

  belongs_to :vignette

  validates :stem, presence: true

  accepts_nested_attributes_for :choices, allow_destroy: true

  has_many :evoke_smarters

  def self.accessible_attributes
    %w(evoke_id topic_id stem tute sort_order difficulty vignette active)
  end

  def choice_mix
    # lets selectively shuffle the answer choices
    # shuffle the CFA and FRM choices freely
    # sort the CPA choices by sort_order
    # sort the CA choices by id

    # disabling choice reordering for questions with I only, I and II etc answer choices
    # questions should have a boolean field to allow shuffling
    # Till then disabling this option

    if evoke_id >= 400_000_000 && evoke_id < 500_000_000
      choices.order(:id).map(&:id)
    else
      correct = choices.right.shuffle.take(rand(1..4))
      incorrect = choices.wrong.shuffle.take(4 - correct.count)
      (correct + incorrect).shuffle.sort_by(&:sort_order).map(&:id)
    end
  end

  def adapt
    lrn = Learning.answered.joins(:user)
                  .where(evoke_id: evoke_id)
                  .where('users.entity IS NULL')
                  .select('100 * count(nullif(correct, true)) / count(*) difficulty_idx')
                  .group(:evoke_id)
                  .having('count(nullif(correct, true)) > 4 and count(nullif(correct, false)) > 4')

    update_attributes difficulty: lrn[0].difficulty_idx.clamp(20, 80), custom: true unless lrn.empty?
  end

  def overlaid_stem
    if overlay.nil?
      (vignette.present? && !vignette.overlay.nil? ? stem_y % eval(vignette.overlay.to_json) : stem).html_safe
    else
      (stem_y % eval(overlay.to_json)).html_safe
    end
  end

  def overlaid_tute
    if overlay.nil?
      tute.html_safe
    else
      (tute_y % (vignette.nil? ? eval(overlay.to_json) : eval(vignette.overlay.to_json))).html_safe
    end
  end

  def overlaid_hint
    if overlay.nil?
      hint.html_safe
    else
      (hint_y % (vignette.nil? ? eval(overlay.to_json) : eval(vignette.overlay.to_json))).html_safe
    end
  end
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  topic_id        :integer          not null, primary key
#  parent_id       :integer
#  symbol          :string           default(""), not null
#  name            :string           not null
#  description     :text
#  sort_order      :integer          default(0), not null
#  ancestry        :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  ancestry_depth  :integer          default(0)
#  parent_topic_id :integer
#  active          :boolean          default(FALSE)
#  weight          :decimal(, )
#  expandable      :boolean          default(FALSE)
#  original_id     :integer
#

class Topic < ActiveRecord::Base

  

  self.primary_key = 'topic_id'

  has_ancestry orphan_strategy: :adopt, cache_depth: true

  default_scope { where(active: true).order(sort_order: :asc) }
  scope :active, -> { where(active: true) }

  # Managers of this topic
  has_many :managements, as: :manageable, dependent: :destroy
  has_many :managers, through: :managements, source: :user

  # Evokes this topic contains
  has_many :evokes, dependent: :destroy

  # Enrolments
  has_many :enrolments, dependent: :destroy
  has_many :enrolled_groups, through: :enrolments, source: :enrollable, source_type: 'Group'
  has_many :enrolled_users, through: :enrolments, source: :enrollable, source_type: 'User'

  has_many :learnings, dependent: :destroy
  has_many :proficiencies, dependent: :destroy

  # validates :name, uniqueness: true

  def self.accessible_attributes
    %w(topic_id parent_topic_id symbol name description sort_order active)
  end

  def max_depth
    subtree.select(&:is_childless?).map(&:depth).max
  end
end

app/models/vignette.rb
# == Schema Information
#
# Table name: vignettes
#
#  id          :integer          not null
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  custom      :boolean          default(FALSE)
#  bodyx       :string
#  body_y      :string
#  overlay     :jsonb
#  original_id :integer
#

class Vignette < ApplicationRecord
  has_many :evokes

  accepts_nested_attributes_for :evokes

  def overlaid
    if overlay.nil?
      body.html_safe
    else
      (body_y % eval(overlay.to_json)).html_safe
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

  end

  include SortableTreeController::Sort
  sortable_tree 'Topic'

  def manage
    # fix ancestry
    #Category.build_ancestry_from_parent_ids!

    #
    @items = Topic.all.arrange(:order => :sort_order)

  end


end

app/controllers/evokes_controller.rb
class EvokesController < ApplicationController
  def show
    @evoke = Evoke.find(params[:id])
    respond_to do |format|
       format.js
   end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include SortableTreeController::Sort
  sortable_tree 'Topic', {parent_method: 'parent'}

  def index
    @topics = Topic.where(parent_id: nil)
    @evokes_count = Evoke.count
    @active_evokes_count = Evoke.where('active is true').count
    @inactive_evokes_count = @evokes_count - @active_evokes_count
  end

  # def show
  #   @topic = Topic.find(params[:topic_id])
  #   respond_to do |format|
  #      format.js
  #  end
  # end

  def manage
    @items = Topic.all.arrange(:order => :sort_order)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_controls.html.haml
= link_to 'Edit', edit_category_url(item)
= link_to 'Delete', category_url(item), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/categories/index.html.haml
%h1 Categories

%ul
  - @items.each do |item|
    %li
      =item.name

app/views/categories/manage.html.haml
= render_sortable_tree(@items, {name_method: :name, sort_url: sort_categories_url, max_levels: 5, controls_partial: 'controls'})

app/views/evokes/_evoke.html.erb
<% if @evoke %>
  <%= @evoke.stem %>
<% else %>
  <p>Select an evoke</p>
<% end %>

app/views/evokes/show.html.erb
<h1>Evokes#show</h1>
<p>Find me in app/views/evokes/show.html.erb</p>

app/views/evokes/show.js.erb
$("#evoke").html("<%= escape_javascript(render partial: 'evoke', locals: { evoke: @evoke } ) %>"); 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eeeee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sortable_tree/_sortable_tree.html.haml
.sortable_tree_wrapper
  %ol.sortable_tree{data: {'sortable-url' => options[:sort_url]} }
    - items.each do |root, children|
      %li{id: "cat_#{root.id}"}
        .item
          /.cell.left
          /  %i.handle
          %h3.cell.left
            =root.send(options[:name_method] || :name)
          .cell.right.controls
            - if options[:controls_partial]
              = render options[:controls_partial], item: root

        = sortable_tree_render_nested_groups(children, options.merge({list_tag: :ol, element_class: 'item'}))



:javascript
  $(document).ready(function(){
    $('.sortable_tree').nestedSortable({
        forceHelperSizeType: true,
        errorClass: 'cantdoit',
        disableNesting: 'cantdoit',
        handle: '> .item',
        helper: 'clone',
        listType: 'ol',
        items: 'li',
        opacity: 0.6,
        placeholder: 'placeholder',
        revert: 250,
        maxLevels: #{options[:max_levels] || 5},
        //tabSize: 20,
        // protectRoot: $(this).data('protect-root'),
        // prevent drag flickers
        tolerance: 'pointer',
        toleranceElement: '> div',
        isTree: true,
        startCollapsed: false,
        //startCollapsed: $(this).data("start-collapsed"),
        relocate: function(){
            //$(this).nestedSortable("disable");
            var data = $(this).nestedSortable("serialize");
            var url = $(this).data("sortable-url");
            // update on server
            $.ajax({
               url: url,
               type: "post",
               data: data
            }).always(function(){
              //$(this).nestedSortable("enable");
              $(this).find('.item').each(function(index){
                if (index % 2){
                  $(this).removeClass('odd').addClass('even');
                }else{
                  $(this).removeClass('even').addClass('odd');
                }
              });
            }).done(function(data){
            }).fail(function(jqXHR, textStatus){
            });
            //$(this).nestedSortable("enable");
        }
    }); // nested tree
  }); // document.ready
Contact GitHub API Training Shop Blog About

app/views/topics/_evokes.html.erb
<% unless @topic.nil? %>
  <p><%= @topic.name %> </p>
  <ul>
    <% @topic.evokes.each do |e| %>
    <li><%= link_to e.stem, evoke_path(e), remote: true %></li>
  <% end %>
</ul>
<% else %>
    <p>Please select a topic</p>
<%end %>

app/views/topics/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<div class="row">
  <div class="col-sm-3">

    <%= nested_attributes(@topics.roots)%>
  </div>
  <div class="col-sm-9">
    <div class="row">
      <p>Some random data will be here </p>
    </div>
    <div class="row">
      <div class="col-sm-4 box">
        <p>All evokes <%= @evokes_count%></p>
      </div>
      <div class="col-sm-4 box">
        <p>Active Evokes <%= @active_evokes_count %></p>
      </div>
      <div class="col-sm-4 box">
        <p>Inactive Evokes <%= @inactive_evokes_count %></p>
     </div>

    </div>
    <div class="row">
      <div class="col-sm-6">
      <p>Evokes will come here<p>
      <div id="evokes">
        <%= render partial: 'topics/evokes' , :locals => {topic: @topics.first }%>
      </div>
    </div>

    <div class="col-sm-6">
      <div id="evoke">
        <%= render partial: "evokes/evoke"%>
      </div>
    </div>

    </div>

  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <%= @topic.id %>
</div>

app/views/topics/show.js.erb
$("#evokes").html("<%= escape_javascript(render partial: 'evokes', locals: { topic: @topic } ) %>"); 